public class Concessionaria {
    List<String> funcionarios = new List<String>();
    List<String> veiculos = new List<String>();
        public String nome;
        public String cpf;
        public String matricula;
        public String marca;
        public String modelo;
        public String placa;
    
    public void funcionarios(String nome, String cpf, String matricula){
        this.nome =nome;
        this.cpf =cpf;
        this.matricula=matricula;
       
        
        
    }
       
        
     }
//sei nem oq foi que eu fiz